# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChatUi.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(857, 520)
        Form.setMinimumSize(QtCore.QSize(592, 520))
        Form.setMaximumSize(QtCore.QSize(2000, 2000))
        Form.setStyleSheet("background-color: rgb(237, 237, 237);\n"
"background-color: rgb(229, 221, 213);")
        self.mediaToolButton = QtWidgets.QToolButton(Form)
        self.mediaToolButton.setGeometry(QtCore.QRect(270, 472, 40, 41))
        self.mediaToolButton.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.mediaToolButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Resources/OpenCamera1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mediaToolButton.setIcon(icon)
        self.mediaToolButton.setIconSize(QtCore.QSize(50, 50))
        self.mediaToolButton.setAutoRaise(False)
        self.mediaToolButton.setObjectName("mediaToolButton")
        self.sendToolButton = QtWidgets.QToolButton(Form)
        self.sendToolButton.setGeometry(QtCore.QRect(805, 480, 41, 26))
        self.sendToolButton.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.sendToolButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Resources/send3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sendToolButton.setIcon(icon1)
        self.sendToolButton.setIconSize(QtCore.QSize(50, 50))
        self.sendToolButton.setObjectName("sendToolButton")
        self.messagesList = QtWidgets.QListWidget(Form)
        self.messagesList.setGeometry(QtCore.QRect(264, 50, 594, 411))
        self.messagesList.setStyleSheet("background-color: rgb(229, 221, 213);\n"
"")
        self.messagesList.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.messagesList.setSelectionRectVisible(True)
        self.messagesList.setObjectName("messagesList")
        self.messageText = QtWidgets.QLineEdit(Form)
        self.messageText.setGeometry(QtCore.QRect(315, 477, 531, 31))
        self.messageText.setStyleSheet("border-radius: 15px;\n"
"padding-left: 10px;\n"
"padding-right: 40px;\n"
"background-color: rgb(255, 255, 255);")
        self.messageText.setText("")
        self.messageText.setObjectName("messageText")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(265, 0, 596, 50))
        self.frame.setStyleSheet("background-color: rgb(237, 237, 237);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.labelStatus = QtWidgets.QLabel(self.frame)
        self.labelStatus.setGeometry(QtCore.QRect(70, 30, 241, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.labelStatus.setFont(font)
        self.labelStatus.setStyleSheet("text-color: \"red\"")
        self.labelStatus.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelStatus.setObjectName("labelStatus")
        self.statusToolButton = QtWidgets.QToolButton(self.frame)
        self.statusToolButton.setGeometry(QtCore.QRect(47, 30, 15, 15))
        self.statusToolButton.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.statusToolButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Resources/green_dot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.statusToolButton.setIcon(icon2)
        self.statusToolButton.setIconSize(QtCore.QSize(50, 50))
        self.statusToolButton.setObjectName("statusToolButton")
        self.labelChatName = QtWidgets.QLabel(self.frame)
        self.labelChatName.setGeometry(QtCore.QRect(65, 5, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.labelChatName.setFont(font)
        self.labelChatName.setWordWrap(True)
        self.labelChatName.setObjectName("labelChatName")
        self.iconToolButton = QtWidgets.QToolButton(self.frame)
        self.iconToolButton.setGeometry(QtCore.QRect(10, 5, 41, 41))
        self.iconToolButton.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.iconToolButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Resources/user_contact.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.iconToolButton.setIcon(icon3)
        self.iconToolButton.setIconSize(QtCore.QSize(50, 50))
        self.iconToolButton.setCheckable(False)
        self.iconToolButton.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.iconToolButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.iconToolButton.setObjectName("iconToolButton")
        self.toolButton = QtWidgets.QToolButton(self.frame)
        self.toolButton.setGeometry(QtCore.QRect(555, 10, 31, 31))
        self.toolButton.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.toolButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Resources/remove_chat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon4)
        self.toolButton.setIconSize(QtCore.QSize(70, 70))
        self.toolButton.setObjectName("toolButton")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 266, 521))
        self.frame_2.setStyleSheet("background-color: rgb(237, 237, 237);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.line = QtWidgets.QFrame(self.frame_2)
        self.line.setGeometry(QtCore.QRect(264, 0, 3, 520))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.userIconButton = QtWidgets.QToolButton(self.frame_2)
        self.userIconButton.setGeometry(QtCore.QRect(10, 10, 41, 41))
        self.userIconButton.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.userIconButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Resources/user-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.userIconButton.setIcon(icon5)
        self.userIconButton.setIconSize(QtCore.QSize(50, 50))
        self.userIconButton.setCheckable(False)
        self.userIconButton.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.userIconButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.userIconButton.setObjectName("userIconButton")
        self.userLabel = QtWidgets.QLabel(self.frame_2)
        self.userLabel.setGeometry(QtCore.QRect(60, 10, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.userLabel.setFont(font)
        self.userLabel.setWordWrap(True)
        self.userLabel.setObjectName("userLabel")
        self.searchContactLabel = QtWidgets.QLineEdit(self.frame_2)
        self.searchContactLabel.setGeometry(QtCore.QRect(20, 70, 231, 31))
        self.searchContactLabel.setStyleSheet("border-radius: 15px;\n"
"padding-left: 10px;\n"
"padding-right: 40px;\n"
"background-color: rgb(255, 255, 255);")
        self.searchContactLabel.setText("")
        self.searchContactLabel.setObjectName("searchContactLabel")
        self.addContactToolButton = QtWidgets.QToolButton(self.frame_2)
        self.addContactToolButton.setGeometry(QtCore.QRect(220, 70, 31, 31))
        self.addContactToolButton.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Resources/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addContactToolButton.setIcon(icon6)
        self.addContactToolButton.setIconSize(QtCore.QSize(28, 28))
        self.addContactToolButton.setObjectName("addContactToolButton")
        self.chatList = QtWidgets.QListWidget(self.frame_2)
        self.chatList.setGeometry(QtCore.QRect(-1, 110, 266, 351))
        self.chatList.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.chatList.setObjectName("chatList")
        self.addGroupToolButton = QtWidgets.QToolButton(self.frame_2)
        self.addGroupToolButton.setGeometry(QtCore.QRect(100, 460, 71, 61))
        self.addGroupToolButton.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("Resources/create_group.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addGroupToolButton.setIcon(icon7)
        self.addGroupToolButton.setIconSize(QtCore.QSize(40, 40))
        self.addGroupToolButton.setObjectName("addGroupToolButton")
        self.logoutToolButton = QtWidgets.QToolButton(self.frame_2)
        self.logoutToolButton.setGeometry(QtCore.QRect(230, 10, 31, 21))
        self.logoutToolButton.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("Resources/shutdown.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logoutToolButton.setIcon(icon8)
        self.logoutToolButton.setIconSize(QtCore.QSize(32, 32))
        self.logoutToolButton.setObjectName("logoutToolButton")
        self.confirmGroupToolButton = QtWidgets.QToolButton(self.frame_2)
        self.confirmGroupToolButton.setEnabled(True)
        self.confirmGroupToolButton.setGeometry(QtCore.QRect(210, 460, 51, 61))
        self.confirmGroupToolButton.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("Resources/confirm.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.confirmGroupToolButton.setIcon(icon9)
        self.confirmGroupToolButton.setIconSize(QtCore.QSize(34, 34))
        self.confirmGroupToolButton.setObjectName("confirmGroupToolButton")
        self.cancelGroupToolButton = QtWidgets.QToolButton(self.frame_2)
        self.cancelGroupToolButton.setGeometry(QtCore.QRect(10, 460, 41, 61))
        self.cancelGroupToolButton.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("Resources/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancelGroupToolButton.setIcon(icon10)
        self.cancelGroupToolButton.setIconSize(QtCore.QSize(40, 40))
        self.cancelGroupToolButton.setObjectName("cancelGroupToolButton")
        self.removeMediaToolButton = QtWidgets.QToolButton(Form)
        self.removeMediaToolButton.setEnabled(False)
        self.removeMediaToolButton.setGeometry(QtCore.QRect(298, 500, 25, 19))
        self.removeMediaToolButton.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("Resources/cancel_red.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeMediaToolButton.setIcon(icon11)
        self.removeMediaToolButton.setObjectName("removeMediaToolButton")
        self.messagesList.raise_()
        self.messageText.raise_()
        self.mediaToolButton.raise_()
        self.sendToolButton.raise_()
        self.frame.raise_()
        self.frame_2.raise_()
        self.removeMediaToolButton.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.messageText.setPlaceholderText(_translate("Form", "Write a message..."))
        self.labelStatus.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600; font-style:normal; color:#7e7e7e;\">online now</span></p></body></html>"))
        self.labelChatName.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:400;\">Christian Cavallo</span></p></body></html>"))
        self.userLabel.setText(_translate("Form", "Noemi Buggea"))
        self.searchContactLabel.setPlaceholderText(_translate("Form", "Search a new contact by email..."))
        self.addContactToolButton.setText(_translate("Form", "..."))
        self.addGroupToolButton.setText(_translate("Form", "..."))
        self.logoutToolButton.setText(_translate("Form", "..."))
        self.confirmGroupToolButton.setText(_translate("Form", "..."))
        self.cancelGroupToolButton.setText(_translate("Form", "..."))
        self.removeMediaToolButton.setText(_translate("Form", "..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
